--
-- PostgreSQL database dump
--


-- Dumped from database version 18.3 (Homebrew)
-- Dumped by pg_dump version 18.3 (Homebrew)




--
-- Name: cooking_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cooking_history (
    id bigint NOT NULL,
    cooked_at timestamp(6) without time zone NOT NULL,
    cost_saved numeric(10,2),
    recipe_id bigint NOT NULL,
    servings_cooked integer NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: cooking_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cooking_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cooking_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ingredient_aliases; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ingredient_aliases (
    id bigint NOT NULL,
    alias character varying(255) NOT NULL,
    ingredient_id bigint NOT NULL
);


--
-- Name: ingredient_aliases_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ingredient_aliases ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ingredient_aliases_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ingredients; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ingredients (
    id bigint NOT NULL,
    canonical_name character varying(255) NOT NULL,
    category character varying(255),
    default_unit character varying(255),
    unit_type character varying(255),
    container_size numeric(38,2),
    container_unit character varying(255),
    CONSTRAINT ingredients_unit_type_check CHECK (((unit_type)::text = ANY ((ARRAY['WEIGHT'::character varying, 'VOLUME'::character varying, 'COUNT'::character varying])::text[])))
);


--
-- Name: ingredients_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ingredients ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ingredients_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pantry_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pantry_items (
    id bigint NOT NULL,
    category character varying(255),
    created_at timestamp(6) without time zone,
    expiry_date date,
    ingredient_name character varying(255) NOT NULL,
    quantity numeric(10,2),
    unit character varying(255),
    updated_at timestamp(6) without time zone,
    canonical_ingredient_id bigint,
    user_id bigint NOT NULL
);


--
-- Name: pantry_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.pantry_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pantry_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recipe_dietary_tags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recipe_dietary_tags (
    recipe_id bigint NOT NULL,
    tag character varying(255),
    CONSTRAINT recipe_dietary_tags_tag_check CHECK (((tag)::text = ANY ((ARRAY['VEGETARIAN'::character varying, 'VEGAN'::character varying, 'GLUTEN_FREE'::character varying, 'DAIRY_FREE'::character varying, 'NUT_FREE'::character varying, 'HIGH_PROTEIN'::character varying, 'LOW_CARB'::character varying])::text[])))
);


--
-- Name: recipe_ingredients; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recipe_ingredients (
    id bigint NOT NULL,
    ingredient_name character varying(255) NOT NULL,
    notes character varying(255),
    is_optional boolean NOT NULL,
    quantity numeric(10,2),
    unit character varying(255),
    canonical_ingredient_id bigint,
    recipe_id bigint NOT NULL
);


--
-- Name: recipe_ingredients_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.recipe_ingredients ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recipe_ingredients_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recipe_steps; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recipe_steps (
    recipe_id bigint NOT NULL,
    step_text character varying(1000),
    step_order integer NOT NULL
);


--
-- Name: recipes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recipes (
    id bigint NOT NULL,
    calories integer,
    cook_time_mins integer,
    cost_per_serve numeric(10,2),
    created_at timestamp(6) without time zone,
    created_by_user_id bigint,
    cuisine character varying(255),
    image_url character varying(255),
    name character varying(255) NOT NULL,
    servings integer,
    source character varying(255) NOT NULL,
    CONSTRAINT recipes_source_check CHECK (((source)::text = ANY ((ARRAY['SEEDED'::character varying, 'SPOONACULAR'::character varying, 'USER_ADDED'::character varying])::text[])))
);


--
-- Name: recipes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.recipes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recipes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_allergy_tags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_allergy_tags (
    user_preferences_id bigint NOT NULL,
    tag character varying(255),
    CONSTRAINT user_allergy_tags_tag_check CHECK (((tag)::text = ANY ((ARRAY['NUTS'::character varying, 'SHELLFISH'::character varying, 'SOY'::character varying, 'EGGS'::character varying, 'DAIRY'::character varying, 'WHEAT'::character varying])::text[])))
);


--
-- Name: user_diet_tags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_diet_tags (
    user_preferences_id bigint NOT NULL,
    tag character varying(255),
    CONSTRAINT user_diet_tags_tag_check CHECK (((tag)::text = ANY ((ARRAY['VEGETARIAN'::character varying, 'VEGAN'::character varying, 'PESCATARIAN'::character varying, 'GLUTEN_FREE'::character varying, 'DAIRY_FREE'::character varying, 'NUT_FREE'::character varying, 'HIGH_PROTEIN'::character varying, 'LOW_CARB'::character varying])::text[])))
);


--
-- Name: user_preferences; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_preferences (
    id bigint NOT NULL,
    budget_per_serve numeric(10,2),
    daily_suggestion_on boolean NOT NULL,
    expiry_alert_days integer NOT NULL,
    text_size character varying(255) NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT user_preferences_text_size_check CHECK (((text_size)::text = ANY ((ARRAY['SMALL'::character varying, 'MEDIUM'::character varying, 'LARGE'::character varying])::text[])))
);


--
-- Name: user_preferences_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_preferences ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_preferences_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_saved_recipes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_saved_recipes (
    id bigint NOT NULL,
    recipe_id bigint NOT NULL,
    saved_at timestamp(6) without time zone NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: user_saved_recipes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_saved_recipes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_saved_recipes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    verification_code character varying(255),
    verification_code_expires_at timestamp(6) without time zone,
    email_verified boolean DEFAULT false NOT NULL,
    verification_attempts integer DEFAULT 0 NOT NULL
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cooking_history cooking_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cooking_history
    ADD CONSTRAINT cooking_history_pkey PRIMARY KEY (id);


--
-- Name: ingredient_aliases ingredient_aliases_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ingredient_aliases
    ADD CONSTRAINT ingredient_aliases_pkey PRIMARY KEY (id);


--
-- Name: ingredients ingredients_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ingredients
    ADD CONSTRAINT ingredients_pkey PRIMARY KEY (id);


--
-- Name: pantry_items pantry_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pantry_items
    ADD CONSTRAINT pantry_items_pkey PRIMARY KEY (id);


--
-- Name: recipe_ingredients recipe_ingredients_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recipe_ingredients
    ADD CONSTRAINT recipe_ingredients_pkey PRIMARY KEY (id);


--
-- Name: recipe_steps recipe_steps_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recipe_steps
    ADD CONSTRAINT recipe_steps_pkey PRIMARY KEY (recipe_id, step_order);


--
-- Name: recipes recipes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recipes
    ADD CONSTRAINT recipes_pkey PRIMARY KEY (id);


--
-- Name: ingredients uk2ebtdyatjoovnu0pnicu0cnd2; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ingredients
    ADD CONSTRAINT uk2ebtdyatjoovnu0pnicu0cnd2 UNIQUE (canonical_name);


--
-- Name: user_saved_recipes uk3yay3qtyrwfi7mqtcj69e32ge; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_saved_recipes
    ADD CONSTRAINT uk3yay3qtyrwfi7mqtcj69e32ge UNIQUE (user_id, recipe_id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: user_preferences ukqy8dkrkc8b34dcgwoq2km43rd; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_preferences
    ADD CONSTRAINT ukqy8dkrkc8b34dcgwoq2km43rd UNIQUE (user_id);


--
-- Name: user_preferences user_preferences_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_preferences
    ADD CONSTRAINT user_preferences_pkey PRIMARY KEY (id);


--
-- Name: user_saved_recipes user_saved_recipes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_saved_recipes
    ADD CONSTRAINT user_saved_recipes_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: recipe_dietary_tags fk37ig6ck822pap0qwpats922s; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recipe_dietary_tags
    ADD CONSTRAINT fk37ig6ck822pap0qwpats922s FOREIGN KEY (recipe_id) REFERENCES public.recipes(id);


--
-- Name: pantry_items fk3meajnwxeiutqupff947oba8v; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pantry_items
    ADD CONSTRAINT fk3meajnwxeiutqupff947oba8v FOREIGN KEY (canonical_ingredient_id) REFERENCES public.ingredients(id);


--
-- Name: ingredient_aliases fk4m9kha18yqm9ojrsvm6jkugcb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ingredient_aliases
    ADD CONSTRAINT fk4m9kha18yqm9ojrsvm6jkugcb FOREIGN KEY (ingredient_id) REFERENCES public.ingredients(id);


--
-- Name: user_allergy_tags fk5a24ilb63hwra8ghsq57eoivn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_allergy_tags
    ADD CONSTRAINT fk5a24ilb63hwra8ghsq57eoivn FOREIGN KEY (user_preferences_id) REFERENCES public.user_preferences(id);


--
-- Name: user_diet_tags fk9jgcnt9yjktfdp88idn4eymnf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_diet_tags
    ADD CONSTRAINT fk9jgcnt9yjktfdp88idn4eymnf FOREIGN KEY (user_preferences_id) REFERENCES public.user_preferences(id);


--
-- Name: pantry_items fkayckcp1th3lq25cdopuc2kw68; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pantry_items
    ADD CONSTRAINT fkayckcp1th3lq25cdopuc2kw68 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: recipe_ingredients fkcqlw8sor5ut10xsuj3jnttkc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recipe_ingredients
    ADD CONSTRAINT fkcqlw8sor5ut10xsuj3jnttkc FOREIGN KEY (recipe_id) REFERENCES public.recipes(id);


--
-- Name: recipe_ingredients fklk8ck6wd7sfh4iqgam2gscnkl; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recipe_ingredients
    ADD CONSTRAINT fklk8ck6wd7sfh4iqgam2gscnkl FOREIGN KEY (canonical_ingredient_id) REFERENCES public.ingredients(id);


--
-- Name: recipe_steps fkof4i3g3aiwgro5ykaf1j28iw1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recipe_steps
    ADD CONSTRAINT fkof4i3g3aiwgro5ykaf1j28iw1 FOREIGN KEY (recipe_id) REFERENCES public.recipes(id);


--
-- PostgreSQL database dump complete
--


